package handlers

// Code generated by routegen; DO NOT EDIT.

import (
	"longheng.io/server/internal/platform/dispatch"
	"longheng.io/server/internal/reference/player"
	"longheng.io/server/pkg/protocol"
)

var genHandlerMetas = []dispatch.HandlerMeta{
	{MsgID: protocol.MessageEnterWorld, Name: "EnterWorld", Description: "Loads the active profile and returns base role state.", AuthRequired: true, PlayerScoped: true, Stateful: true, Authorized: true, Idempotent: true, RouteGroup: "player"},
	{MsgID: protocol.MessageAddCurrency, Name: "AddCurrency", Description: "Adds currency to the active profile and returns the new balance.", AuthRequired: true, PlayerScoped: true, Stateful: true, Authorized: true, Idempotent: true, RouteGroup: "player", ProfileOperation: string(player.ProfileOperationAddCurrency), CriticalEvent: true, Durability: "eventlog", DurabilityOwner: "profile"},
	{MsgID: protocol.MessageReadMail, Name: "ReadMail", Description: "Marks one mailbox item read and returns mailbox unread count.", AuthRequired: true, PlayerScoped: true, Stateful: true, Authorized: true, Idempotent: true, RouteGroup: "player", CriticalEvent: true, Durability: "eventlog", DurabilityOwner: "profile"},
}

func GeneratedHandlerMetas() []dispatch.HandlerMeta {
	return append([]dispatch.HandlerMeta(nil), genHandlerMetas...)
}

func Default(ctx Context) []Handler {
	return []Handler{
		EnterWorld{Players: ctx.Players},
		AddCurrency{Players: ctx.Players},
		ReadMail{Players: ctx.Players},
	}
}

func (h EnterWorld) Meta() dispatch.HandlerMeta {
	return genHandlerMetas[0]
}

func (h AddCurrency) Meta() dispatch.HandlerMeta {
	return genHandlerMetas[1]
}

func (h ReadMail) Meta() dispatch.HandlerMeta {
	return genHandlerMetas[2]
}
